# Generated by Django 5.1 on 2024-08-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assistant_id", models.CharField(max_length=100)),
                ("conversation_id", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["-conversation_id"],
            },
        ),
    ]
