# Generated by Django 5.1 on 2024-08-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-relevance_conversation_id"]},
        ),
        migrations.RenameField(
            model_name="conversation",
            old_name="conversation_id",
            new_name="relevance_conversation_id",
        ),
        migrations.RenameField(
            model_name="conversation",
            old_name="assistant_id",
            new_name="vapi_assistant_id",
        ),
    ]
