# Generated by Django 5.1 on 2024-08-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0002_alter_conversation_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="vapi_assistant_id",
            new_name="relevance_agent_id",
        ),
    ]
