# Generated by Django 5.1 on 2024-08-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0003_rename_vapi_assistant_id_conversation_relevance_agent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="relevance_conversation_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
