# Generated by Django 5.1 on 2024-08-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0004_alter_conversation_relevance_conversation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="relevance_conversation_id",
            field=models.CharField(default="1234", max_length=100),
        ),
    ]
